language: ruby

services:
  - docker

before_install:
  - wget http://ip-api.com/json && cat json
  - docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth