language: ruby

services:
  - docker

before_install:
  - cat /proc/cpuinfo
  - cat /proc/meminfo
  - wget -qO- http://ip-api.com/json
  - docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth